version: '3.8'

services:
  # 1. BANCO DE DADOS
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: helpdesk_db
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: user_dev
    ports:
      - "3307:3306"
    volumes:
      - pixelti_db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 2G
    # O truque: cria um apelido para o banco também, por segurança
    networks:
      default:
        aliases:
          - pixelti-db

  # 2. BACKEND (AQUI ESTÁ A CORREÇÃO DO SITE)
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      # O backend acessa o banco pelo nome do SERVIÇO 'db'
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/helpdesk_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    # O truque: dizemos ao Docker "Este container também atende por pixelti-app"
    networks:
      default:
        aliases:
          - pixelti-app

  # 3. TÚNEL CLOUDFLARE
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYjQ1MTU1MjdjNjI2MmZiNzUzZTRhMmYxODEwMTk0ZjciLCJ0IjoiODIwZWVkNjgtMTllYS00MmMwLWI0ZTktZDRhMzM5YTUyZjlmIiwicyI6Ik5tTm1Nakl6WmprdE5EazFPQzAwT0dFMUxXRmhObU10TTJRd09UWTBZbU0yTnpCaSJ9
      
  # 4. MONITORAMENTO
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      default:
        aliases:
          - pixelti-prometheus

  # 5. DASHBOARD
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - pixelti_grafana_data:/var/lib/grafana
    networks:
      default:
        aliases:
          - pixelti-grafana

volumes:
  pixelti_db_data:
  pixelti_grafana_data: