version: '3.8'

services:
  # 1. BANCO DE DADOS
  db:
    image: mysql:8.0
    container_name: techxmicro-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: techxmicro_db
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: user_dev
    ports:
      - "3309:3306" # Porta 3309 externa para não conflitar com outros MySQLs
    volumes:
      - techxmicro_db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 2G

  # 2. BACKEND (Spring Boot)
  app:
    build: .
    container_name: techxmicro-app
    restart: always
    ports:
      - "8083:8080" # Porta 8083 externa conforme seu pedido
    depends_on:
      - db
    environment:
      # CRÍTICO: DB_HOST deve ser exatamente o nome do serviço acima 'db'
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=techxmicro_db
      - DB_USER=root
      - DB_PASSWORD=admin
    # Adicionado para garantir que o container app consiga resolver o nome 'db'
    links:
      - db

  # 3. TÚNEL CLOUDFLARE
  tunnel:
    image: cloudflare/cloudflared
    container_name: techxmicro-tunnel
    restart: always
    command: tunnel run
    environment:
      # Seu Token atualizado finalizando em ...T1RVeSJ9
      - TUNNEL_TOKEN=eyJhIjoiYjQ1MTU1MjdjNjI2MmZiNzUzZTRhMmYxODEwMTk0ZjciLCJ0IjoiY2NmYjBiMTctNDFhZi00NGExLTk0NmQtZWRkYjNjY2ExOWI2IiwicyI6IlpUTXdaREU0TWpjdE5HVXlOUzAwWW1aaUxUbGlNbUl0WmpjNE16WmpNVFU0T1RVeSJ9

  # 4. MONITORAMENTO
  prometheus:
    image: prom/prometheus
    container_name: techxmicro-prometheus
    restart: always
    ports:
      - "9093:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # 5. DASHBOARD
  grafana:
    image: grafana/grafana
    container_name: techxmicro-grafana
    restart: always
    ports:
      - "3003:3000"
    depends_on:
      - prometheus
    volumes:
      - techxmicro_grafana_data:/var/lib/grafana

volumes:
  techxmicro_db_data:
  techxmicro_grafana_data: